name: Build and Deploy
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
      NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
      NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
      NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}
      NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}
      NEXT_PUBLIC_FIREBASE_APP_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}
      NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID }}
      FIREBASE_SERVICE_ACCOUNT_HEALTH_ASSESSMENT_01: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_HEALTH_ASSESSMENT_01 }}
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          
      - name: Debug Environment
        run: |
          echo "Checking Firebase Config (first few chars)..."
          echo "API_KEY starts with: ${NEXT_PUBLIC_FIREBASE_API_KEY:0:4}..."
          echo "AUTH_DOMAIN starts with: ${NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN:0:4}..."
          echo "PROJECT_ID: $NEXT_PUBLIC_FIREBASE_PROJECT_ID"
          
      - name: Install Dependencies
        run: npm install
      
      - name: Build
        run: npm run build
